[package]
name = "twenty-forty-eight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.8"
bevy_egui = "0.16"
rand = "0.8.5"
futures-lite = "1.12"
rfd = "0.10"
nn = "0.1.6"