[package]
name = "twenty-forty-eight"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11"
bevy-inspector-egui = "0.20"
rand = "0.8"
futures-lite = "2.0"
rfd = "0.12"
nn = "0.1.6"
